dunglas/vaccin.click

- background_scripts/index.js
- manifest.json
Voir https://twitter.com/garoo/status/1394570353486204929?s=20.
> fix: n'ouvrir l'onglet de réservation qu'une seule fois

- background_scripts/index.js
- content_scripts/doctolib/book.js
- manifest.json
Closes https://github.com/dunglas/vaccin.click/issues/11.
> feat: afficher une notification quand un créneau est trouvé

- content_scripts/doctolib/book.js
- manifest.json
Ajoute le support de la liste déroulante "motif de catégorie".
Un grand merci à @floriangagnard pour les infos de debug. Close https://github.com/dunglas/vaccin.click/issues/23.
> feat: ajout du support de la catégorie de motif

- content_scripts/doctolib/book.js
* question de nouveau patient
* tranches d'âge
* "Vaccination Pfizer"
Fixes #20
> feat: Fix a few issues with centers

- content_scripts/doctolib/book.js
Finalement, j'ai utilisé une regexp pour matcher plus de cas sur la partie "catégorie" :shrug:
> Fix some more cases

- content_scripts/doctolib/book.js
Example: https://www.doctolib.fr/centre-de-sante/paris/sos-medecins-paris?pid=practice-165129
> feat: support SOS Médecins

- content_scripts/doctolib/book.js
- content_scripts/doctolib/search.js
Plusieurs corrections :
* correction d'un conflit entre le script d'ajout du bouton et le script de réservation
* correction d'un bug sélectionnant la 3ème dose quand elle est dispo au lieu de la première
> fix: divers bugs

- .eslintrc.json
- .github/workflows/lint.yml
- browser_action/index.css
- manifest.json
Lance `prettier` pour les CS et le linter d'extensions de Mozilla.
> ci: mise en place d'une CI minimale

- content_scripts/doctolib/book.js
J'ai aussi simplifié `waitForSelector` pour éviter toutes les conditions autour de `resolve`.
> feat: ajout de diagnostic en cas d'erreur pour le clic sur un slot et la popup finale

- background_scripts/index.js
- browser_action/index.css
- content_scripts/doctolib/book.js
- content_scripts/doctolib/search.js
- j'ai légèrement augmenté la taille du tableau pour voir mieux les logs
- 1 typo
- des broutilles facultatives au niveau du code qui vont rien changer, à garder ou non
> Small fixes

- content_scripts/doctolib/book.js
Je trouvais que certaines actions mettaient parfois du temps à démarrer, alors j'ai ajusté un peu les timers.
> feat: Réduction de quelques timers

- .gitignore
- content_scripts/doctolib/book.js
À partir du 31 mai, on peut réserver tous les créneaux. https://twitter.com/GuillaumeRozier/status/1397844292845068288
> feat: autoriser la réservation des créneaux dispos après le 31 mai

- content_scripts/doctolib/book.js
Puisque j'ai réduit le timeout récemment, il est sans doute important
d'augmenter le nombre d'erreurs possibles.
> feat: Augmente le nombre de checks

- background_scripts/JobQueue.js
- background_scripts/index.js
Tout est dans le titre, on enlève les jolies petites secondes pour des ms !
> feat: Use only ms

- background_scripts/JobQueue.js
- background_scripts/index.js
- browser_action/index.js
- On enlève les jolies petites secondes pour des ms !
- On affiche les logs dans l'autre sens
... dsl, ca devait être 2 PR... j'me suis planté sur les branches :(
> feat: Use ms + Revert logs display

- content_scripts/doctolib/book.js
> feat: Support du centre de Nogent-sur-Marne

- content_scripts/doctolib/book.js
> Pour les centres qui proposent une dose unique, bien ignorer cette option

- content_scripts/doctolib/book.js
Pull request qui permet de matcher la chaîne de caractère accentuée "août".
Voir issue #73 
Par contre, j'ai tenté d'utiliser eslint mais je n'arrive pas à le configurer comme il faut pour le lancer.
>  fix: Match Accented Letters with Regular Expressions

- background_scripts/index.js
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getURL.
> fix: deprecated API calls

- browser_action/index.html
- browser_action/index.js
- commons/AppStatus.js
- content_scripts/doctolib/book.js
Add choice to select vaccine injection moderna or pfizer
Reply to #82
> feat: add vaccine injection choice moderna or pfizer

- browser_action/index.js
- commons/AppStatus.js
I forget a little thing in my last pr #87
> fix: vaccine-injection

- browser_action/index.html
- commons/AppStatus.js
- content_scripts/doctolib/book.js
- pfizer instead of moderna as default
> fix: use most common defaults

- _locales/de/messages.json
- _locales/fr/messages.json
- background_scripts/index.js
- browser_action/index.html
- browser_action/index.js
- commons/VCLocalStorage.js
- content_scripts/doctolib/book.js
- content_scripts/doctolib/search.js
- manifest.json
Here we go, one step closer to becoming international. Now we just need to translate the landing page and we're done :)
- Add i18n
- All french texts extracted into locale file
- Add German translations
> feat: add i18n support
